# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
  # aaaa
  
  displayName: 'Setup ue4 docker'
  
- task: Docker@2
  inputs:
    repository: 'https://github.com/adamrehn/ue4-docker.git'
    command: 'build'
    Dockerfile: '**/ue4docker/dockerfiles/ue4-full/linux/Dockerfile'
