# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  DOCKER_BUILDKIT: 1

steps:
- script: |
  git clone https://github.com/adamrehn/ue4-docker.git
  
  displayName: 'Clone UE4 dockerfile'
  

- task: Docker@2
  inputs:
    repository: 'https://github.com/adamrehn/ue4-docker.git'
    command: 'build'
    Dockerfile: '**/ue4docker/dockerfiles/ue4-full/linux/Dockerfile'
