# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install python3 python3-dev python3-pip python3-setuptools

    sudo pip3 install ue4-docker
    sudo ue4-docker setup

    ue4-docker build 4.26.0 --no-engine
    ue4-docker clean --source
    # ue4 build

  displayName: 'Setup ue4 docker'
